<?php $catalogSearchHelper =  $this->helper('catalogsearch'); ?>
<div class="input-box">
<!--	<label for="search">--><?php //echo $this->__('Search:') ?><!--</label>-->
	<input id="search" type="search" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" class="input-text required-entry" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>" placeholder="<?php echo $this->__('Search entire store here...') ?>" />
<!--	<button type="submit" title="--><?php //echo $this->__('Search') ?><!--" class="button search-button"><span><span>--><?php //echo $this->__('Search') ?><!--</span></span></button>-->
</div>