<form action="<?php echo Mage::helper('queen_skip')->getSearchUrl() ?>" method="POST">
<div class="input-box">
	<input id="postcode-search" type="search" name="postcode-search"  class="input-text required-entry" placeholder="<?php echo $this->__('Enter your postcode...') ?>" />
	<button type="submit" title="<?php echo $this->__('Search') ?>" class="button search-button"><span><span><?php echo $this->__('Search') ?></span></span></button>
</div>
</form>