<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 6/18/15
 * Time: 8:19 PM
 */ 
/* @var $installer Mage_Core_Model_Resource_Setup */
$installer = $this;

$installer->startSetup();
$tableName = $installer->getTable('queen_skip/town');
$installer->run("--
insert  into `$tableName`(`code`,`name`) values ('&nbsp;','Please select');
insert  into `$tableName`(`code`,`name`) values ('AB','Aberdeen');
insert  into `$tableName`(`code`,`name`) values ('AL','St Albans');
insert  into `$tableName`(`code`,`name`) values ('B','Birmingham');
insert  into `$tableName`(`code`,`name`) values ('BA','Bath');
insert  into `$tableName`(`code`,`name`) values ('BB','Blackburn');
insert  into `$tableName`(`code`,`name`) values ('BD','Bradford');
insert  into `$tableName`(`code`,`name`) values ('BH','Bournemouth');
insert  into `$tableName`(`code`,`name`) values ('BL','Bolton');
insert  into `$tableName`(`code`,`name`) values ('BN','Brighton');
insert  into `$tableName`(`code`,`name`) values ('BR','Bromley');
insert  into `$tableName`(`code`,`name`) values ('BS','Bristol');
insert  into `$tableName`(`code`,`name`) values ('BT','Belfast');
insert  into `$tableName`(`code`,`name`) values ('CA','Carlisle');
insert  into `$tableName`(`code`,`name`) values ('CB','Cambridge');
insert  into `$tableName`(`code`,`name`) values ('CF','Cardiff');
insert  into `$tableName`(`code`,`name`) values ('CH','Chester');
insert  into `$tableName`(`code`,`name`) values ('CM','Chelmsford');
insert  into `$tableName`(`code`,`name`) values ('CO','Colchester');
insert  into `$tableName`(`code`,`name`) values ('CR','Croydon');
insert  into `$tableName`(`code`,`name`) values ('CT','Canterbury');
insert  into `$tableName`(`code`,`name`) values ('CV','Coventry');
insert  into `$tableName`(`code`,`name`) values ('CW','Crewe');
insert  into `$tableName`(`code`,`name`) values ('DA','Dartford');
insert  into `$tableName`(`code`,`name`) values ('DD','Dundee');
insert  into `$tableName`(`code`,`name`) values ('DE','Derby');
insert  into `$tableName`(`code`,`name`) values ('DG','Dumfries and Galloway');
insert  into `$tableName`(`code`,`name`) values ('DH','Durham');
insert  into `$tableName`(`code`,`name`) values ('DL','Darlington');
insert  into `$tableName`(`code`,`name`) values ('DN','Doncaster');
insert  into `$tableName`(`code`,`name`) values ('DT','Dorchester');
insert  into `$tableName`(`code`,`name`) values ('DY','Dudley');
insert  into `$tableName`(`code`,`name`) values ('E','London E');
insert  into `$tableName`(`code`,`name`) values ('EC','London EC');
insert  into `$tableName`(`code`,`name`) values ('EH','Edinburgh');
insert  into `$tableName`(`code`,`name`) values ('EN','Enfield');
insert  into `$tableName`(`code`,`name`) values ('EX','Exeter');
insert  into `$tableName`(`code`,`name`) values ('FK','Falkirk and Stirling');
insert  into `$tableName`(`code`,`name`) values ('FY','Blackpool, Fylde');
insert  into `$tableName`(`code`,`name`) values ('G','Glasgow');
insert  into `$tableName`(`code`,`name`) values ('GL','Gloucester');
insert  into `$tableName`(`code`,`name`) values ('GU','Guildford');
insert  into `$tableName`(`code`,`name`) values ('GY','Guernsey');
insert  into `$tableName`(`code`,`name`) values ('HA','Harrow');
insert  into `$tableName`(`code`,`name`) values ('HD','Huddersfield');
insert  into `$tableName`(`code`,`name`) values ('HG','Harrogate');
insert  into `$tableName`(`code`,`name`) values ('HP','Hemel Hempstead');
insert  into `$tableName`(`code`,`name`) values ('HR','Hereford');
insert  into `$tableName`(`code`,`name`) values ('HS','Outer Hebrides');
insert  into `$tableName`(`code`,`name`) values ('HU','Hull');
insert  into `$tableName`(`code`,`name`) values ('HX','Halifax');
insert  into `$tableName`(`code`,`name`) values ('IG','Ilford');
insert  into `$tableName`(`code`,`name`) values ('IM','Isle of Man');
insert  into `$tableName`(`code`,`name`) values ('IP','Ipswich');
insert  into `$tableName`(`code`,`name`) values ('IV','Inverness');
insert  into `$tableName`(`code`,`name`) values ('JE','Jersey');
insert  into `$tableName`(`code`,`name`) values ('KA','Kilmarnock');
insert  into `$tableName`(`code`,`name`) values ('KT','Kingston upon Thames');
insert  into `$tableName`(`code`,`name`) values ('KW','Kirkwall');
insert  into `$tableName`(`code`,`name`) values ('KY','Kirkcaldy');
insert  into `$tableName`(`code`,`name`) values ('L','Liverpool');
insert  into `$tableName`(`code`,`name`) values ('LA','Lancaster');
insert  into `$tableName`(`code`,`name`) values ('LD','Llandrindod Wells');
insert  into `$tableName`(`code`,`name`) values ('LE','Leicester');
insert  into `$tableName`(`code`,`name`) values ('LL','Llandudno');
insert  into `$tableName`(`code`,`name`) values ('LN','Lincoln');
insert  into `$tableName`(`code`,`name`) values ('LS','Leeds');
insert  into `$tableName`(`code`,`name`) values ('LU','Luton');
insert  into `$tableName`(`code`,`name`) values ('M','Manchester');
insert  into `$tableName`(`code`,`name`) values ('ME','Rochester, Medway');
insert  into `$tableName`(`code`,`name`) values ('MK','Milton Keynes');
insert  into `$tableName`(`code`,`name`) values ('ML','Motherwell');
insert  into `$tableName`(`code`,`name`) values ('N','London N');
insert  into `$tableName`(`code`,`name`) values ('NE','Newcastle upon Tyne');
insert  into `$tableName`(`code`,`name`) values ('NG','Nottingham');
insert  into `$tableName`(`code`,`name`) values ('NN','Northampton');
insert  into `$tableName`(`code`,`name`) values ('NP','Newport');
insert  into `$tableName`(`code`,`name`) values ('NR','Norwich');
insert  into `$tableName`(`code`,`name`) values ('NW','London NW');
insert  into `$tableName`(`code`,`name`) values ('OL','Oldham');
insert  into `$tableName`(`code`,`name`) values ('OX','Oxford');
insert  into `$tableName`(`code`,`name`) values ('PA','Paisley');
insert  into `$tableName`(`code`,`name`) values ('PE','Peterborough');
insert  into `$tableName`(`code`,`name`) values ('PH','Perth');
insert  into `$tableName`(`code`,`name`) values ('PL','Plymouth');
insert  into `$tableName`(`code`,`name`) values ('PO','Portsmouth');
insert  into `$tableName`(`code`,`name`) values ('PR','Preston');
insert  into `$tableName`(`code`,`name`) values ('RG','Reading');
insert  into `$tableName`(`code`,`name`) values ('RH','Redhill');
insert  into `$tableName`(`code`,`name`) values ('RM','Romford');
insert  into `$tableName`(`code`,`name`) values ('S','Sheffield');
insert  into `$tableName`(`code`,`name`) values ('SA','Swansea');
insert  into `$tableName`(`code`,`name`) values ('SE','London SE');
insert  into `$tableName`(`code`,`name`) values ('SG','Stevenage');
insert  into `$tableName`(`code`,`name`) values ('SK','Stockport');
insert  into `$tableName`(`code`,`name`) values ('SL','Slough');
insert  into `$tableName`(`code`,`name`) values ('SM','Sutton');
insert  into `$tableName`(`code`,`name`) values ('SN','Swindon');
insert  into `$tableName`(`code`,`name`) values ('SO','Southampton');
insert  into `$tableName`(`code`,`name`) values ('SP','Salisbury');
insert  into `$tableName`(`code`,`name`) values ('SR','Sunderland');
insert  into `$tableName`(`code`,`name`) values ('SS','Southend on Sea');
insert  into `$tableName`(`code`,`name`) values ('ST','Stoke-on-Trent');
insert  into `$tableName`(`code`,`name`) values ('SW','London SW');
insert  into `$tableName`(`code`,`name`) values ('SY','Shrewsbury');
insert  into `$tableName`(`code`,`name`) values ('TA','Taunton');
insert  into `$tableName`(`code`,`name`) values ('TD','Galashiels, Tweeddale');
insert  into `$tableName`(`code`,`name`) values ('TF','Telford');
insert  into `$tableName`(`code`,`name`) values ('TN','Tonbridge');
insert  into `$tableName`(`code`,`name`) values ('TQ','Torquay');
insert  into `$tableName`(`code`,`name`) values ('TR','Truro');
insert  into `$tableName`(`code`,`name`) values ('TS','Cleveland, Teesside');
insert  into `$tableName`(`code`,`name`) values ('TW','Twickenham');
insert  into `$tableName`(`code`,`name`) values ('UB','Southall, Uxbridge');
insert  into `$tableName`(`code`,`name`) values ('W','London W');
insert  into `$tableName`(`code`,`name`) values ('WA','Warrington');
insert  into `$tableName`(`code`,`name`) values ('WC','London WC');
insert  into `$tableName`(`code`,`name`) values ('WD','Watford');
insert  into `$tableName`(`code`,`name`) values ('WF','Wakefield');
insert  into `$tableName`(`code`,`name`) values ('WN','Wigan');
insert  into `$tableName`(`code`,`name`) values ('WR','Worcester');
insert  into `$tableName`(`code`,`name`) values ('WS','Walsall');
insert  into `$tableName`(`code`,`name`) values ('WV','Wolverhampton');
insert  into `$tableName`(`code`,`name`) values ('YO','York');
insert  into `$tableName`(`code`,`name`) values ('ZE','Lerwick, Zetland');
--");

$installer->endSetup();